################################ -*- Ruby -*- #################################
# Common tasks
#

desc "Generate README.md"
task "readme" do
  sh "emacs", "-batch", "-l", "../../el2markdown/el2markdown.el", \
  "../faceup.el", "-f", "el2markdown-write-readme"
end

desc "Generating html"
task "html" => ["readme"] do
  File.open(File.join("..", "README.html"), "w") do |fh|
    fh.puts("<head>")
    fh.puts("  <meta charset=\"UTF-8\">")
    fh.puts("</head>")
  end
  sh "Markdown.pl ../README.md >> ../README.html"
end
